import dotenv from "dotenv";
import { resolve } from "node:path";

dotenv.config({
  path: resolve(process.cwd(), ".env"),
});

const {
	BACKEND_NODE_ENV,
	BACKEND_PORT,
	BACKEND_SALT_ROUNDS,
	BACKEND_JWT_SECRET,
	BACKEND_JWT_EXPIRY,
	BACKEND_REFRESH_TOKEN_SECRET,
	BACKEND_REFRESH_TOKEN_EXPIRY	,
	FRONTEND_DOMAIN,
} = process.env;

export const Config = {
	BACKEND_NODE_ENV: String(BACKEND_NODE_ENV),
	BACKEND_PORT: Number(BACKEND_PORT),
	BACKEND_SALT_ROUNDS: Number(BACKEND_SALT_ROUNDS),
	BACKEND_JWT_SECRET: String(BACKEND_JWT_SECRET),
	BACKEND_JWT_EXPIRY: String(BACKEND_JWT_EXPIRY),
	BACKEND_REFRESH_TOKEN_SECRET: String(BACKEND_REFRESH_TOKEN_SECRET),
	BACKEND_REFRESH_TOKEN_EXPIRY: String(BACKEND_REFRESH_TOKEN_EXPIRY),
	FRONTEND_DOMAIN: String(FRONTEND_DOMAIN),
};
